version: '3'

services:
    hook:
       container_name: mailgun-webhook
       build: .
       restart: always
#       environment:
#            - ME_CONFIG_MONGODB_SERVER=mongo
#            - ME_CONFIG_MONGODB_PORT=27017
#            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
#            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
#            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
#            - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
#            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
       expose:
        - "80"
       networks:
        - mongo-express-network
networks:
    mongo-express-network:
        external:
            name: www-network
